# Generated by Django 3.1.7 on 2021-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='booklists.Genre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='static/cover/picturenotfound.jpg', upload_to='book_covers'),
        ),
    ]
