# Generated by Django 3.1.7 on 2021-04-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
