# Generated by Django 3.1.7 on 2021-04-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0002_auto_20210405_1721'),
        ('booklists', '0002_auto_20210405_1624'),
    ]

    operations = [
    ]
