# Generated by Django 3.1.7 on 2021-04-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0002_auto_20210404_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='/images/picturenotfound.jpg', upload_to='book_covers'),
        ),
    ]
