# Generated by Django 3.1.7 on 2021-04-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0003_merge_20210405_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
