# Generated by Django 3.1.7 on 2021-04-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0006_auto_20210406_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
